# SvarttDupePlugin Configuration!

# Enable or disable detection of players removing items from ItemFrames
# NOTE! if itemframe-dupe and piston-dupe is enabled at same twice, it will dupe it on both instances!

# Dupes the content of an itemframe when a player pops the item out
itemframe-dupe:
  enabled: false
  success_rate: 50 # int in percent! (1-100)

# Dupes the content of an itemframe when a player pops the item out - on an extended piston
piston-dupe:
  enabled: false
  success_rate: 50 # int in percent! (1-100)
